"""Durable evidence workflow: quality gates, bounded model search, review approval.

Does not execute arbitrary shell/code generated by an LLM. Every step is an
allowlisted scientific action. Approvals are explicit, auditable human acts.
"""
from __future__ import annotations
from datetime import datetime, timezone
from hashlib import sha256
from pathlib import Path
from uuid import uuid4
import json
import os
import traceback
import numpy as np
from .science import prepare_data, fit_and_evaluate, cross_shortlist


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _write(path: Path, obj: object):
    tmp = path.with_suffix(path.suffix + '.tmp')
    tmp.write_text(json.dumps(obj, indent=2, default=str, allow_nan=False), encoding='utf-8')
    os.replace(tmp, path)


class AuditLog:
    """Local hash-chained events (tamper-evident, NOT tamper-proof without external anchoring)."""
    def __init__(self, folder: Path):
        self.path = folder / 'events.jsonl'

    def append(self, actor: str, action: str, details: dict):
        prev = ''
        if self.path.exists():
            lines = self.path.read_text(encoding='utf8').splitlines()
            if lines:
                prev = json.loads(lines[-1])['hash']
        event = {'timestamp': _now(), 'actor': actor, 'action': action,
                 'details': details, 'previous_hash': prev}
        content = json.dumps(event, sort_keys=True, separators=(',', ':'), default=str)
        event['hash'] = sha256(content.encode()).hexdigest()
        with self.path.open('a', encoding='utf8') as f:
            f.write(json.dumps(event, sort_keys=True)+'\n')
            f.flush()
            os.fsync(f.fileno())

    def verify(self) -> bool:
        previous = ''
        for line in self.path.read_text(encoding='utf8').splitlines():
            record = json.loads(line)
            digest = record.pop('hash')
            if record['previous_hash'] != previous:
                return False
            if sha256(json.dumps(record, sort_keys=True, separators=(',', ':'), default=str).encode()).hexdigest() != digest:
                return False
            previous = digest
        return True


def _require_job(root: str | Path, job_id: str) -> Path:
    if len(job_id) != 32 or any(c not in '0123456789abcdef' for c in job_id):
        raise ValueError('Invalid job identifier')
    folder = Path(root).resolve() / job_id
    if not (folder / 'manifest.json').is_file():
        raise FileNotFoundError('Breeding campaign not found')
    return folder


def get_campaign(root: str | Path, job_id: str) -> dict:
    folder = _require_job(root, job_id)
    result = json.loads((folder/'manifest.json').read_text(encoding='utf8'))
    result['audit_chain_valid'] = AuditLog(folder).verify()
    return result


def approve_campaign(root: str | Path, job_id: str, actor: str, justification: str) -> dict:
    """Approve *review of shortlist* only; no physical cross/variety deployment."""
    folder = _require_job(root, job_id)
    manifest = json.loads((folder/'manifest.json').read_text(encoding='utf8'))
    if manifest['status'] != 'AWAITING_HUMAN_REVIEW' or not manifest['scientific_checks']['positive_skill']:
        raise ValueError('Only campaigns passing predictive gates can be approved for human-reviewed shortlist use')
    actor, justification = actor.strip(), justification.strip()
    if len(actor)<3 or len(justification)<15:
        raise ValueError('Reviewer and substantive justification are required')
    if not AuditLog(folder).verify():
        raise ValueError('Audit chain integrity check failed')
    AuditLog(folder).append(actor,'approve_cross_shortlist',{'justification':justification,
        'scope':'approval of shortlist for breeder consideration, not field deployment'})
    manifest['status']='REVIEWED_SHORTLIST'
    manifest['approval']={'reviewer': actor,'justification':justification,'time':_now()}
    _write(folder/'manifest.json',manifest)
    return get_campaign(root,job_id)


def run_campaign(genotypes: bytes, phenotypes: bytes, trait: str, output_root: str|Path,
                 group: str|None = None, direction: str = 'max', seed: int = 42,
                 max_kinship: float = .30, diversity_weight: float = .15) -> dict:
    """Synchronous audited evaluation; nothing runs after the command/request terminates."""
    if direction not in ('max','min') or len(trait)>120 or not trait.strip():
        raise ValueError('Invalid trait or selection direction')
    if not isinstance(seed, int) or not 0 <= seed <= 2**32-1:
        raise ValueError('Seed out of range')
    root = Path(output_root).resolve()
    root.mkdir(parents=True,exist_ok=True)
    job_id = uuid4().hex
    folder = root/job_id
    folder.mkdir(mode=0o700)
    audit = AuditLog(folder)
    manifest = {'job_id':job_id, 'product':'GURUDEV.ai', 'version':'0.3.0',
                'workflow':'qc -> fit/nested_cv -> skill gate -> cross triage -> human review',
                'created_utc':_now(),'status':'RUNNING', 'trait':trait,
                'input_digests':{'genotypes_sha256': sha256(genotypes).hexdigest(),
                                 'phenotypes_sha256':sha256(phenotypes).hexdigest()},
                'parameters':{'group_column':group, 'direction':direction,'seed':seed,
                              'max_genomic_relationship':max_kinship,
                              'diversity_weight':diversity_weight},
                'software':{'numpy':np.__version__}, 'agent_actions':[], 'approval':None}
    _write(folder/'manifest.json',manifest)
    audit.append('orchestrator','campaign_created', {'trait':trait,'input_sha256':manifest['input_digests']})
    try:
        data = prepare_data(genotypes,phenotypes,trait,group)
        manifest['qc'] = data.qc
        audit.append('data_quality_agent','input_validated',data.qc)
        manifest['agent_actions'].append('data_quality_agent: validated IDs, diploid codes, sample alignment and missingness')
        results = fit_and_evaluate(data,seed)
        audit.append('genomic_prediction_agent','nested_validation_completed',{
            'model_metrics':results['model_metrics'],'baseline_metrics':results['baseline_metrics'],
            'positive_skill':results['positive_skill_gate'],
            'selected_penalty':results['selected_penalty'], 'folds': results['folds']})
        manifest['agent_actions'].append('genomic_prediction_agent: fitted/tuned GBLUP with training-fold-only SNP QC')
        results['out_of_fold'].to_csv(folder/'out_of_fold_predictions.csv',index=False)
        results['candidate_table'].to_csv(folder/'candidate_predictions.csv',index=False)
        crosses = cross_shortlist(data,results,direction=direction,
            diversity_weight=diversity_weight,max_kinship=max_kinship)
        _write(folder/'cross_shortlist.json',crosses)
        from .figures import generate_evidence_figures
        artifacts=generate_evidence_figures(folder,results['out_of_fold'],
                           results['candidate_table'],results['model_metrics'],trait,direction)
        audit.append('figure_agent','evidence_figures_generated',{'figures':artifacts,
           'interpretation':'plots show internal CV, not a claim of prospective performance'})
        from .external import save_model
        save_model(folder,data,results)
        audit.append('model_registry_agent','trained_model_safely_serialized',
                     {'format':'npz_numpy_nonpickle','markers':results['markers_used_final']})
        manifest['evaluation'] = {'model':results['model_metrics'], 'train_fold_mean_baseline':results['baseline_metrics'],
            'folds':results['folds'],'selected_penalty':results['selected_penalty'],
            'markers_used_in_final_model':results['markers_used_final'],
            'crosses_shortlisted':len(crosses), 'validation_type':results['validation_type'],
            'evidence_figures':artifacts}
        manifest['scientific_checks']={'nested_cv':True,'training_only_snp_filtering':True,
                    'train_mean_baseline':True,'positive_skill':results['positive_skill_gate'],
                    'prospective_external_validation':False, 'genotype_qc_for_crosses':True}
        if results['positive_skill_gate']:
            manifest['status']='AWAITING_HUMAN_REVIEW'
            manifest['agent_actions'].append('decision_agent: proposed research cross shortlist; requires breeder approval')
            audit.append('decision_agent','recommend_review',{'crosses':len(crosses),
                'status':'review_required','no_automatic_breeding_actions':True})
        else:
            manifest['status']='SCIENTIFIC_HOLD'
            manifest['agent_actions'].append('decision_agent: stopped cross proposals because model did not beat fold mean baseline')
            audit.append('decision_agent','failed_skill_gate',{'crosses_released':0})
        report = report_markdown(manifest, crosses)
        (folder/'scientific_report.md').write_text(report,encoding='utf8')
        _write(folder/'manifest.json', manifest)
        audit.append('validation_agent','verified_outputs', {'files':[
            'scientific_report.md','out_of_fold_predictions.csv','candidate_predictions.csv','cross_shortlist.json','trained_gblup_model.npz'],
            'status':manifest['status']})
    except Exception as exc:
        manifest['status']='FAILED'
        manifest['failure']={'error_type':type(exc).__name__, 'message':str(exc),
                'guidance':'Inspect data headers, identifiers, marker QC and validation grouping. No automatic scientific reinterpretation.'}
        audit.append('orchestrator','campaign_failed',manifest['failure'])
        _write(folder/'manifest.json',manifest)
        # Preserve inspectable failure state and raise to the caller.
        raise
    return get_campaign(root,job_id)


def report_markdown(m:dict,crosses:list[dict]) -> str:
    qc = m['qc']
    ev = m['evaluation']
    mm,bm = ev['model'],ev['train_fold_mean_baseline']
    lines = ['# GURUDEV.ai | Breeding Campaign Scientific Report','',
       f"**Run:** `{m['job_id']}` | **Trait:** {m['trait']} | **Status:** {m['status']}",
       '', '## Data integrity',
       f"- {qc['n_genotyped']} genotyped lines, {qc['n_phenotyped']} phenotyped; {qc['n_unphenotyped_candidates']} prediction candidates.",
       f"- {qc['n_markers_raw']} raw SNPs; {ev['markers_used_in_final_model']} after full-training QC.",
       f"- Genotype missing fraction: {qc['overall_missing_genotype_fraction']:.3%}.",
       '', '## Model evidence',
       '- Method: genomic best linear unbiased prediction via VanRaden-style genomic relationship kernel, kernel ridge solution.',
       '- SNP imputation, allele frequencies, filtering and tuning are recalculated inside training folds.',
       f"- Internal {ev['validation_type']} GBLUP RMSE: **{mm['rmse']:.4f}**; fold training-mean baseline: **{bm['rmse']:.4f}**.",
       f"- GBLUP Pearson r: {mm['pearson_r']}; R²: {mm['r2']:.4f}.",
       f"- Chosen genomic kernel regularization: {ev['selected_penalty']}.",
       f"- Positive predictive skill gate: **{m['scientific_checks']['positive_skill']}**.",
       '', '## Candidate crosses (research hypotheses only)',
       f"- Shortlisted: {len(crosses)}. Every item requires breeder review; NO simulated progeny performance or release claims.",
       '- Selection ranks additive midparent proxies and a weighted genomic relatedness bonus. Expected marker F1 heterozygosity is descriptive only.',
       '- Relationships rely on the evaluated panel, sample coding and allele alignment; no dominance, epistasis or G×E model is inferred.',
       '', '## Scientific restrictions',
       '- **Internal CV is NOT external prospective validation.** Random folds may overestimate performance in related germplasm.',
       '- A single genotype trait value must come from an appropriate experimental model (e.g., BLUEs) if trials are replicated.',
       '- For germplasm from distinct populations or environments use group / future-year / location holdouts.',
       '- Individual fitted training predictions are not independent validation predictions.',
       '- Human validation is mandatory before field crossing or deployment. No external actions are executed.',
       '', '## Reproducibility and audit',
       f"- Seed: {m['parameters']['seed']}, genotype SHA256: `{m['input_digests']['genotypes_sha256']}`.",
       '- See `manifest.json`, `events.jsonl`, `out_of_fold_predictions.csv`, `candidate_predictions.csv`, `trained_gblup_model.npz`, and `cross_shortlist.json`.',
       '- Figures A and B are archived as publication-resolution PNG and editable-vector PDF (internal validation only).',
       '- Audit event hashes are locally chained, not externally notarized.', '']
    return '\n'.join(lines)
